/**
  Here is a sequence:

  1. `'1'`, first number is 1
  2. `'11'`, since previous number has One(1) 1
  3. `'21'`, since previous number has Two(2) 1s
  4. `'1211'`, since previous number has One(1) 2 and One(1) 1
  5. `'111221'`, since previous number has One(1) 1, One(1) 2, Two(2) 1s
  6. `'312211'`, since previous number has Three(3) 1s, Two(2) 2s, One(1) 1
  7. ....

  As explained above, the sequence is generated by counting the digits of previous number.
  Please create `getNthNum(n)` to return the n-th number string in the sequence, n starts from 1.
 */

/*-------------------- 用例测试 -------------------------*/
getNthNum(1); // '1'
getNthNum(5); // '111221'
getNthNum(20); // '11131221131211132221232112111312111213111213211231132132211211131221131211221321123113213221123113112221131112311332211211131221131211132211121312211231131112311211232221121321132132211331121321231231121113112221121321133112132112312321123113112221121113122113121113123112112322111213211322211312113211'

/* -------------------- Code solution -------------------- */
// helper function:
const transform = (num) => {
  let currentDigit = '';
  let currentCount = 0;
  let result = '';
  for (let i = 0; i <= num.length; i++) {
    if (num[i] === currentDigit) {
      currentCount += 1;
    } else {
      if (currentCount > 0) {
        result += currentCount + currentDigit;
      }

      currentDigit = num[i];
      currentCount = 1;
    }
  }
  return result;
};

/**
 * @param {number} n - integer
 * @returns {string}
 * Main function:
 */
function getNthNum(n) {
  let num = '1';

  while (n > 1) {
    num = transform(num);
    n -= 1;
  }

  return num;
}
